In [1]:
import numpy as np
import torch

In [2]:
tensor1 = torch.randint(0, 2, (4, 3))
tensor2 = torch.randint(0, 2, (8, 3))

In [3]:
tensor1

tensor([[0, 0, 1],
        [1, 1, 1],
        [0, 1, 0],
        [1, 1, 0]])

In [4]:
tensor2

tensor([[1, 0, 1],
        [0, 0, 1],
        [0, 0, 1],
        [0, 0, 0],
        [1, 0, 0],
        [1, 1, 0],
        [1, 0, 1],
        [0, 0, 0]])

In [5]:
M = torch.mul(tensor1.flatten()[:, None], tensor2.flatten()[None, :])
M

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0],
        [1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0],
        [1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0],
        [1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0],
        [1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [6]:
M2 = M.reshape(4, 3, -1, 3).permute(0, 2, 1, 3).reshape(-1, 3, 3)
M2

tensor([[[0, 0, 0],
         [0, 0, 0],
         [1, 0, 1]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 1]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 1]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [1, 0, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [1, 1, 0]],

        [[0, 0, 0],
         [0, 0, 0],
         [1, 0, 1]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 0, 1],
         [1, 0, 1],
         [1, 0, 1]],

        [[0, 0, 1],
         [0, 0, 1],
         [0, 0, 1]],

        [[0, 0, 1],
         [0, 0, 1],
         [0, 0, 1]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 0, 0],
         [1, 0, 0],
         [1, 0, 0]],

        [[1, 1, 0],
         [1, 1, 0],
         [1, 1, 0]],

        [[1, 0, 1],
         [1, 0, 1],
         [1, 0, 1]],

        [[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]],

        

In [7]:
torch.diagonal(M2, dim1=1, dim2=2).max(1).values.reshape(4, 8)

tensor([[1, 1, 1, 0, 0, 0, 1, 0],
        [1, 1, 1, 0, 1, 1, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 1, 1, 1, 0]])

In [12]:
M3 = M.reshape(4, 3, -1, 3).permute(0, 2, 1, 3).reshape(4, -1, 3, 3)
M3

tensor([[[[0, 0, 0],
          [0, 0, 0],
          [1, 0, 1]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 1]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 1]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [1, 0, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [1, 1, 0]],

         [[0, 0, 0],
          [0, 0, 0],
          [1, 0, 1]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]]],


        [[[1, 0, 1],
          [1, 0, 1],
          [1, 0, 1]],

         [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]],

         [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]],

         [[0, 0, 0],
          [0, 0, 0],
          [0, 0, 0]],

         [[1, 0, 0],
          [1, 0, 0],
          [1, 0, 0]],

         [[1, 1, 0],
          [1, 1, 0],
          [1, 1, 0]],

         [[1, 0, 1],
          [1, 0, 1],
          [1, 0, 1]],

         [[0, 0, 0],
  

In [16]:
torch.diagonal(M3, dim1=2, dim2=3).max(2).values

tensor([[1, 1, 1, 0, 0, 0, 1, 0],
        [1, 1, 1, 0, 1, 1, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 1, 1, 1, 0]])

In [8]:
torch.matmul(tensor1, tensor2.t()).clamp(max=1)

tensor([[1, 1, 1, 0, 0, 0, 1, 0],
        [1, 1, 1, 0, 1, 1, 1, 0],
        [0, 0, 0, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 1, 1, 1, 0]])