In [8]:
import numpy as np
import math

In [9]:
def get_parts_matrix(max_dist, n_parts, seed):
        # return parts as binary mask on 7 x 7 grid to ease evaluation
        np.random.seed(seed)
        n_row = 7
        n_pix_per_cell = 50
        part_locs = [np.random.randint(350, size=2) for _ in range(n_parts)]
        parts = np.zeros((n_parts, n_row, n_row))
        if max_dist == 0:
            for part_loc, part_id in zip(part_locs, range(n_parts)):
                x_coord = int(part_loc[0] // n_pix_per_cell)
                y_coord = int(part_loc[1] // n_pix_per_cell)
                if part_id != -1:
                    parts[part_id, y_coord, x_coord] = 1
        else:
            for part_loc, part_id in zip(part_locs, range(n_parts)):
                if part_id == -1:
                    continue
                x_coord_part = part_loc[0]
                y_coord_part = part_loc[1]
                for cell_x, cell_y in np.ndindex(n_row, n_row):
                    x_coord_cell = cell_x * n_pix_per_cell
                    y_coord_cell = cell_y * n_pix_per_cell
                    dx = max(x_coord_cell - x_coord_part, 0, x_coord_part - x_coord_cell - n_pix_per_cell)
                    dy = max(y_coord_cell - y_coord_part, 0, y_coord_part - y_coord_cell - n_pix_per_cell)
                    dist = math.sqrt(dx * dx + dy * dy) / n_pix_per_cell
                    # print(f"{cell_x}, {cell_y}, {dist}, {1 - dist / max_dist}, {max(parts[part_id, cell_y, cell_x], 1 - dist / max_dist)}")
                    parts[part_id, cell_y, cell_x] = max(parts[part_id, cell_y, cell_x], 1 - dist / max_dist)
        return parts

In [10]:
get_parts_matrix(0, 1, 0)

array([[[0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [11]:
get_parts_matrix(3.0, 1, 0)

array([[[0.18666667, 0.52      , 0.85333333, 1.        , 0.81333333,
         0.48      , 0.14666667],
        [0.1864208 , 0.51958351, 0.85197598, 0.98      , 0.81226496,
         0.47961553, 0.14643232],
        [0.11323309, 0.40397614, 0.61743555, 0.64666667, 0.60038908,
         0.37131531, 0.07640798],
        [0.        , 0.16219864, 0.29784459, 0.31333333, 0.28841335,
         0.13865738, 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ]]])

In [12]:
get_parts_matrix(1, 1, 0)

array([[[0.        , 0.        , 0.56      , 1.        , 0.44      ,
         0.        , 0.        ],
        [0.        , 0.        , 0.55592793, 0.94      , 0.43679489,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        , 0.        ]]])

: 